# SPDX-FileCopyrightText: 2026 ash_double_entry contributors <https://github.com/ash-project/ash_double_entry/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshDoubleEntry.Transaction do
  @moduledoc """
  An extension for creating a double-entry ledger transaction (header).

  A `Transaction` groups N `Entry` rows that together must satisfy the
  fundamental double-entry invariant: `Σ debits == Σ credits` per
  currency. See the multi-leg journal entries tutorial for full details.
  """

  @transaction %Spark.Dsl.Section{
    name: :transaction,
    schema: [
      account_resource: [
        type: {:spark, Ash.Resource},
        doc: "The Account resource Entries belong to.",
        required: true
      ],
      entry_resource: [
        type: {:spark, Ash.Resource},
        doc: "The Entry resource Entries are stored in.",
        required: true
      ],
      balance_resource: [
        type: {:spark, Ash.Resource},
        doc: "The Balance resource. Required for entry-driven balance updates.",
        required: true
      ],
      create_accept: [
        type: {:list, :atom},
        doc: "Extra attributes accepted by the autogenerated `:post` action.",
        default: []
      ],
      pre_check_identities_with: [
        type: {:spark, Ash.Domain},
        doc: "A domain to use to precheck generated identities."
      ]
    ]
  }

  @sections [@transaction]

  @transformers [
    AshDoubleEntry.Transaction.Transformers.AddStructure
  ]

  use Spark.Dsl.Extension,
    sections: @sections,
    transformers: @transformers
end
