defmodule AshDoubleEntry.Test.Repo.Migrations.MultiLeg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transactions, primary_key: false) do
      add(:id, :binary, null: false, primary_key: true)

      add(:posted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :reverses_transaction_id,
        references(:transactions,
          column: :id,
          name: "transactions_reverses_transaction_id_fkey",
          type: :binary
        )
      )
    end

    create table(:entries, primary_key: false) do
      add(:id, :binary, null: false, primary_key: true)
      add(:side, :text, null: false)
      add(:amount, :money_with_currency, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :transaction_id,
        references(:transactions,
          column: :id,
          name: "entries_transaction_id_fkey",
          type: :binary
        ), null: false)

      add(
        :account_id,
        references(:accounts, column: :id, name: "entries_account_id_fkey", type: :uuid),
        null: false
      )
    end

    alter table(:balances) do
      add(
        :entry_id,
        references(:entries, column: :id, name: "balances_entry_id_fkey", type: :binary)
      )
    end

    create unique_index(:balances, [:account_id, :entry_id],
             name: "balances_unique_account_entry_index"
           )
  end

  def down do
    drop(constraint(:balances, "balances_entry_id_fkey"))

    drop_if_exists(
      unique_index(:balances, [:account_id, :entry_id],
        name: "balances_unique_account_entry_index"
      )
    )

    alter table(:balances) do
      remove(:entry_id)
    end

    drop(constraint(:entries, "entries_transaction_id_fkey"))

    drop(constraint(:entries, "entries_account_id_fkey"))

    drop(table(:entries))

    drop(constraint(:transactions, "transactions_reverses_transaction_id_fkey"))

    drop(table(:transactions))
  end
end
