defmodule AshDoubleEntry.Test.Repo.Migrations.AddEntryAppFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entries) do
      add(:line_item_id, :text)
      add(:internal_note, :text)
    end
  end

  def down do
    alter table(:entries) do
      remove(:internal_note)
      remove(:line_item_id)
    end
  end
end
