defmodule AshDoubleEntry.Test.Repo.Migrations.AddTransferTransactionId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transfers) do
      add(:transaction_id, :binary)
    end
  end

  def down do
    alter table(:transfers) do
      remove(:transaction_id)
    end
  end
end
