defmodule AshDoubleEntry.Test.Repo.Migrations.AddEntryTimestamp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entries) do
      add(:timestamp, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:entries) do
      remove(:timestamp)
    end
  end
end
